### ISSUE TITLE
[Bug] Elf Hosted Jackett, 4.2.1, configurated, never shown during the search for any movie

### ISSUE THREAD

**Issue by michael1900** [aymene69/stremio-jackett#181]
**Describe the bug**
Simply, i configurated it with API RD like always before and installed. But form last 2 version i never seen it in the list of addons when i choose a movie

**To Reproduce**
Install it, choose a movie and never you will see Jackett in Addon list when you choose a movie

**Expected behavior**
See Jsckett addon in the list of addons when i choose a movie, like with Torrentio, Mediafusion, Torbox, Jackettio, etc..

**Your system info (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 132.0.6834.15
 - Docker or Node ? What?

**Comment by victorgveloso** [comment]
RealDebrid no longer supports the endpoint to check if content is cached. Did you try non-cached links? 

Anyways, since the report is about Elf-hosted instances, the bug might not be reproducible in self-hosted machines without further details. I suggest you to provide an example of stream that returns no result for stremio-jackett but works for Jackettio. Perhaps, that will help us identify the issue.

If you are getting results but they are fewer than Jackettio, that is a known bug whose progress you can follow in #176

**Comment by michael1900** [comment]
Hey, any news?

**Comment by michael1900** [comment]
Any news?

**Comment by icenoir** [comment]
I have the same problem with the self-hosted version. I am using the docker setup with Torbox. 
Despite reading in the container terminal that jackett gets the results, on stremio the addon isnt listed when I search for a movie or tvseries, like the screenshots of the other user above.
Can you please check guys?

**Comment by victorgveloso** [comment]
I'm just a user like you guys. Except I submitted a PR, which is yet to be accepted/rejected. 

@aymene69 is the core developer who is most suited for fixing this bug and accepting contributions.

I would be happy to work on this issue, but I’d like some assurance that the approval process won’t result in indefinite delays. And I cannot fix an issue I cannot replicate.

PS: self-hosted + Torbox should support caching like self-hosted + Premiumize and I still cannot replicate this issue with Premiumize. 

@icenoir Could you please try installing [my fork](https://github.com/victorgveloso/stremio-jackett/) and see if the issue is solved there?

**Comment by michael1900** [comment]
> I'm just a user like you guys. Except I submitted a PR, which is yet to be accepted/rejected.
> 
> @aymene69 is the core developer who is most suited for fixing this bug and accepting contributions.
> 
> I would be happy to work on this issue, but I’d like some assurance that the approval process won’t result in indefinite delays. And I cannot fix an issue I cannot replicate.
> 
> PS: self-hosted + Torbox should support caching like self-hosted + Premiumize and I still cannot replicate this issue with Premiumize.
> 
> @icenoir Could you please try installing [my fork](https://github.com/victorgveloso/stremio-jackett/) and see if the issue is solved there?

But your fork works with Real Debrid? I mean it finds movies, etc?

**Comment by victorgveloso** [comment]
It's a fork of the latest version plus three patches (#178, #179, and #180). I do not intend to maintain it. It is meant to be integrated into the upstream project (this repository). However, the core developer is inactive since I submitted the PR.
So answering your questions...
> But your fork works with Real Debrid?

There is no way I can test it since I do not have a Real Debrid account. Though, for features unrelated to the aforementioned patches, it should work as the upstream project (this repository).
> It finds movies, etc?

It works perfectly in Premiumize and should work with other supported services (AllDebrid, Real Debrid, and Torbox)
> When this patch can be on Elf Hosted?

AFAIK, the only thing preventing them to be on Elf Hosted is @aymene69's inactivity.

> I mean the other addons now have been fixed and they find stuff. 
- Jackettio [does not support Torbox](https://github.com/arvida42/jackettio/issues/43) and [has bugs with Premiumize](https://github.com/arvida42/jackettio/issues/42).
- Comet [does not support foreign language search](https://github.com/g0ldyy/comet/issues/137).
- KnightCrawler also [does not seem to support foreign language search](https://github.com/knightcrawler-stremio/knightcrawler/issues/50)
- MediaFusion [does not support Jackett](https://github.com/mhdzumair/MediaFusion/issues/310).

What works for you might not work for others...

**Comment by michael1900** [comment]
> It's a fork of the latest version plus three patches (#178, #179, and #180). I do not intend to maintain it. It is meant to be integrated into the upstream project (this repository). However, the core developer is inactive since I submitted the PR. So answering your questions...
> 
> > But your fork works with Real Debrid?
> 
> There is no way I can test it since I do not have a Real Debrid account. Though, for features unrelated to the aforementioned patches, it should work as the upstream project (this repository).
> 
> > It finds movies, etc?
> 
> It works perfectly in Premiumize and should work with other supported services (AllDebrid, Real Debrid, and Torbox)
> 
> > When this patch can be on Elf Hosted?
> 
> AFAIK, the only thing preventing them to be on Elf Hosted is @aymene69's inactivity.
> 
> > I mean the other addons now have been fixed and they find stuff.
> 
> * Jackettio [does not support Torbox](https://github.com/arvida42/jackettio/issues/43) and [has bugs with Premiumize](https://github.com/arvida42/jackettio/issues/42).
> * Comet [does not support foreign language search](https://github.com/g0ldyy/comet/issues/137).
> * KnightCrawler [does not seem to support foreign language search too](https://github.com/knightcrawler-stremio/knightcrawler/issues/50)
> * MediaFusion [does not support Jackett](https://github.com/mhdzumair/MediaFusion/issues/310).
> 
> What works for you might not work for others...

How to use your fork publicly since the updated version is not available on elfhosted?

**Comment by victorgveloso** [comment]
> How to use your fork publicly since the updated version is not available on elfhosted?

You will need docker and docker-compose installed.

You can [clone my fork](https://github.com/victorgveloso/stremio-jackett.git) and create the following file in the root folder:

```yaml
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=Host(`traefik.YOURHOSTNAME`)"
      - "traefik.http.routers.monitor.entrypoints=web,websecure"
      - "traefik.http.routers.monitor.service=api@internal"
      - "traefik.http.routers.monitor.tls=true"
      - "traefik.http.routers.monitor.tls.certresolver=production"
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:local
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - ./data:/config
      - ./blackhole:/downloads
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.jackett.entrypoints=web,websecure"
      - "traefik.http.routers.jackett.rule=Host(`jackett.YOURHOSTNAME`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.tls.certresolver=production"
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=debug
      - HEADLESS=true
    networks:
      - traefik_default
    ports:
      - 8191:8191
    restart: unless-stopped
  stremio-addon-jackett:
    build:
      context: source
      dockerfile: Dockerfile
    image: stremio-addon-jackett:local
    container_name: stremio-addon-jackett
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.stremio-addon-jackett.entrypoints=web,websecure"
      - "traefik.http.routers.stremio-addon-jackett.rule=Host(`stremio-jackett.YOURHOSTNAME`)"
      - "traefik.http.services.stremio-addon-jackett.loadbalancer.server.port=3000"
      - "traefik.http.routers.stremio-addon-jackett.tls=true"
      - "traefik.http.routers.stremio-addon-jackett.tls.certresolver=production"
    environment:
      - DISABLE_JACKETT_IMDB_SEARCH=true
    restart: unless-stopped

networks:
  traefik_default:
```

Name the file `docker-compose.yml` and replace YOURHOSTNAME with your domain.

If you want to use HTTPS rather than HTTP, you can also create a folder `/etc/traefik` in the host machine with an empty subfolder `/etc/traefik/certs` and a file `traefik.yml` containing:

```yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: noreply@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: noreply@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: true
  file:
    directory: /etc/traefik
    watch: true
```

After that, in the folder where you cloned my fork, open the terminal and run the following command: `docker compose up -d`

The server should start and be ready to use shortly. You can check the logs by running `docker compose logs`.

That is a simplification and an adaptation of the process implemented at https://github.com/aymene69/stremio-jackett/blob/main/deployment/install.sh for my fork. 

As I said, it should work fine but I do not intend to support it. Let's hope that @aymene69 will resume their maintenance activity in this project.
